version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - "3307:3306"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books-network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    env_file:
      - ../.env.docker
    networks:
      - books-network

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"   # Exponemos Nginx en el puerto 3000
    depends_on:
      - backend
    networks:
      - books-network

networks:
  books-network:
    driver: bridge

# Para ejecutarlo:
# cd backend
# docker-compose -f backend/docker/docker-compose.yml up --build

