version: '3.8'

services:
  mariadb-test:
    image: mariadb:10.7
    container_name: mariadb-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - "3308:3306"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books-test-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 15




  backend-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-test
    depends_on:
      mariadb-test:
        condition: service_healthy
    env_file:
      - ../.env
    command: npm run test:integration
    networks:
      - books-test-network

networks:
  books-test-network:
    driver: bridge


# Para ejecutarlo:
# docker-compose -f docker/docker-compose.test.yml up --build