name: Test and Build Backend and Frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with Docker Compose
        run: |
          docker-compose -f backend/docker/docker-compose.test.yml up --build --abort-on-container-exit

      - name: Build backend Docker image
        working-directory: backend
        run: |
          docker build -t backend-image -f docker/Dockerfile .

      - name: Build frontend Docker image
        working-directory: frontend
        run: |
          docker build -t frontend-image -f Dockerfile .